// Code generated by go-swagger; DO NOT EDIT.

package pipeline_service

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/kubeflow/pipelines/backend/api/v2beta1/go_http_client/pipeline_model"
)

// PipelineServiceGetPipelineVersionByNameReader is a Reader for the PipelineServiceGetPipelineVersionByName structure.
type PipelineServiceGetPipelineVersionByNameReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PipelineServiceGetPipelineVersionByNameReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewPipelineServiceGetPipelineVersionByNameOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewPipelineServiceGetPipelineVersionByNameDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewPipelineServiceGetPipelineVersionByNameOK creates a PipelineServiceGetPipelineVersionByNameOK with default headers values
func NewPipelineServiceGetPipelineVersionByNameOK() *PipelineServiceGetPipelineVersionByNameOK {
	return &PipelineServiceGetPipelineVersionByNameOK{}
}

// PipelineServiceGetPipelineVersionByNameOK describes a response with status code 200, with default header values.
//
// A successful response.
type PipelineServiceGetPipelineVersionByNameOK struct {
	Payload *pipeline_model.V2beta1PipelineVersion
}

// IsSuccess returns true when this pipeline service get pipeline version by name o k response has a 2xx status code
func (o *PipelineServiceGetPipelineVersionByNameOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this pipeline service get pipeline version by name o k response has a 3xx status code
func (o *PipelineServiceGetPipelineVersionByNameOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this pipeline service get pipeline version by name o k response has a 4xx status code
func (o *PipelineServiceGetPipelineVersionByNameOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this pipeline service get pipeline version by name o k response has a 5xx status code
func (o *PipelineServiceGetPipelineVersionByNameOK) IsServerError() bool {
	return false
}

// IsCode returns true when this pipeline service get pipeline version by name o k response a status code equal to that given
func (o *PipelineServiceGetPipelineVersionByNameOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the pipeline service get pipeline version by name o k response
func (o *PipelineServiceGetPipelineVersionByNameOK) Code() int {
	return 200
}

func (o *PipelineServiceGetPipelineVersionByNameOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /apis/v2beta1/pipelines/{pipeline_id}/versions/names/{name}][%d] pipelineServiceGetPipelineVersionByNameOK %s", 200, payload)
}

func (o *PipelineServiceGetPipelineVersionByNameOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /apis/v2beta1/pipelines/{pipeline_id}/versions/names/{name}][%d] pipelineServiceGetPipelineVersionByNameOK %s", 200, payload)
}

func (o *PipelineServiceGetPipelineVersionByNameOK) GetPayload() *pipeline_model.V2beta1PipelineVersion {
	return o.Payload
}

func (o *PipelineServiceGetPipelineVersionByNameOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(pipeline_model.V2beta1PipelineVersion)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewPipelineServiceGetPipelineVersionByNameDefault creates a PipelineServiceGetPipelineVersionByNameDefault with default headers values
func NewPipelineServiceGetPipelineVersionByNameDefault(code int) *PipelineServiceGetPipelineVersionByNameDefault {
	return &PipelineServiceGetPipelineVersionByNameDefault{
		_statusCode: code,
	}
}

// PipelineServiceGetPipelineVersionByNameDefault describes a response with status code -1, with default header values.
//
// An unexpected error response.
type PipelineServiceGetPipelineVersionByNameDefault struct {
	_statusCode int

	Payload *pipeline_model.GoogleRPCStatus
}

// IsSuccess returns true when this pipeline service get pipeline version by name default response has a 2xx status code
func (o *PipelineServiceGetPipelineVersionByNameDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this pipeline service get pipeline version by name default response has a 3xx status code
func (o *PipelineServiceGetPipelineVersionByNameDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this pipeline service get pipeline version by name default response has a 4xx status code
func (o *PipelineServiceGetPipelineVersionByNameDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this pipeline service get pipeline version by name default response has a 5xx status code
func (o *PipelineServiceGetPipelineVersionByNameDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this pipeline service get pipeline version by name default response a status code equal to that given
func (o *PipelineServiceGetPipelineVersionByNameDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the pipeline service get pipeline version by name default response
func (o *PipelineServiceGetPipelineVersionByNameDefault) Code() int {
	return o._statusCode
}

func (o *PipelineServiceGetPipelineVersionByNameDefault) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /apis/v2beta1/pipelines/{pipeline_id}/versions/names/{name}][%d] PipelineService_GetPipelineVersionByName default %s", o._statusCode, payload)
}

func (o *PipelineServiceGetPipelineVersionByNameDefault) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /apis/v2beta1/pipelines/{pipeline_id}/versions/names/{name}][%d] PipelineService_GetPipelineVersionByName default %s", o._statusCode, payload)
}

func (o *PipelineServiceGetPipelineVersionByNameDefault) GetPayload() *pipeline_model.GoogleRPCStatus {
	return o.Payload
}

func (o *PipelineServiceGetPipelineVersionByNameDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(pipeline_model.GoogleRPCStatus)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
