// Code generated by go-swagger; DO NOT EDIT.

package pipeline_service

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewPipelineServiceGetPipelineVersionByNameParams creates a new PipelineServiceGetPipelineVersionByNameParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPipelineServiceGetPipelineVersionByNameParams() *PipelineServiceGetPipelineVersionByNameParams {
	return NewPipelineServiceGetPipelineVersionByNameParamsWithTimeout(cr.DefaultTimeout)
}

// NewPipelineServiceGetPipelineVersionByNameParamsWithTimeout creates a new PipelineServiceGetPipelineVersionByNameParams object
// with the ability to set a timeout on a request.
func NewPipelineServiceGetPipelineVersionByNameParamsWithTimeout(timeout time.Duration) *PipelineServiceGetPipelineVersionByNameParams {
	return &PipelineServiceGetPipelineVersionByNameParams{
		inner: innerParams{
			timeout: timeout,
		},
	}
}

// NewPipelineServiceGetPipelineVersionByNameParamsWithContext creates a new PipelineServiceGetPipelineVersionByNameParams object
// with the ability to set a context for a request.
//
// Deprecated: use the operation call with context to pass the context instead of [PipelineServiceGetPipelineVersionByNameParams].
func NewPipelineServiceGetPipelineVersionByNameParamsWithContext(ctx context.Context) *PipelineServiceGetPipelineVersionByNameParams {
	return &PipelineServiceGetPipelineVersionByNameParams{
		inner: innerParams{
			ctx: ctx,
		},
	}
}

// NewPipelineServiceGetPipelineVersionByNameParamsWithHTTPClient creates a new PipelineServiceGetPipelineVersionByNameParams object
// with the ability to set a custom HTTPClient for a request.
func NewPipelineServiceGetPipelineVersionByNameParamsWithHTTPClient(client *http.Client) *PipelineServiceGetPipelineVersionByNameParams {
	return &PipelineServiceGetPipelineVersionByNameParams{
		HTTPClient: client,
	}
}

/*
PipelineServiceGetPipelineVersionByNameParams contains all the parameters to send to the API endpoint

	for the pipeline service get pipeline version by name operation.

	Typically these are written to a http.Request.
*/
type PipelineServiceGetPipelineVersionByNameParams struct {

	// Name.
	//
	// Required input. Name of the pipeline version to be retrieved.
	Name string

	// PipelineID.
	//
	// Required input. ID of the parent pipeline.
	PipelineID string

	HTTPClient *http.Client

	inner innerParams
}

// WithDefaults hydrates default values in the pipeline service get pipeline version by name params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PipelineServiceGetPipelineVersionByNameParams) WithDefaults() *PipelineServiceGetPipelineVersionByNameParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the pipeline service get pipeline version by name params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PipelineServiceGetPipelineVersionByNameParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the pipeline service get pipeline version by name params.
func (o *PipelineServiceGetPipelineVersionByNameParams) WithTimeout(timeout time.Duration) *PipelineServiceGetPipelineVersionByNameParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the pipeline service get pipeline version by name params.
func (o *PipelineServiceGetPipelineVersionByNameParams) SetTimeout(timeout time.Duration) {
	o.inner.timeout = timeout
}

// WithContext adds the context to the pipeline service get pipeline version by name params.
//
// Deprecated: use the operation call with context to pass the context instead of [PipelineServiceGetPipelineVersionByNameParams].
func (o *PipelineServiceGetPipelineVersionByNameParams) WithContext(ctx context.Context) *PipelineServiceGetPipelineVersionByNameParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the pipeline service get pipeline version by name params.
//
// Deprecated: use the operation call with context to pass the context instead of [PipelineServiceGetPipelineVersionByNameParams].
func (o *PipelineServiceGetPipelineVersionByNameParams) SetContext(ctx context.Context) {
	o.inner.ctx = ctx
}

// WithHTTPClient adds the HTTPClient to the pipeline service get pipeline version by name params.
func (o *PipelineServiceGetPipelineVersionByNameParams) WithHTTPClient(client *http.Client) *PipelineServiceGetPipelineVersionByNameParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the pipeline service get pipeline version by name params.
func (o *PipelineServiceGetPipelineVersionByNameParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithName adds the name to the pipeline service get pipeline version by name params.
func (o *PipelineServiceGetPipelineVersionByNameParams) WithName(name string) *PipelineServiceGetPipelineVersionByNameParams {
	o.SetName(name)
	return o
}

// SetName adds the name to the pipeline service get pipeline version by name params.
func (o *PipelineServiceGetPipelineVersionByNameParams) SetName(name string) {
	o.Name = name
}

// WithPipelineID adds the pipelineID to the pipeline service get pipeline version by name params.
func (o *PipelineServiceGetPipelineVersionByNameParams) WithPipelineID(pipelineID string) *PipelineServiceGetPipelineVersionByNameParams {
	o.SetPipelineID(pipelineID)
	return o
}

// SetPipelineID adds the pipelineId to the pipeline service get pipeline version by name params.
func (o *PipelineServiceGetPipelineVersionByNameParams) SetPipelineID(pipelineID string) {
	o.PipelineID = pipelineID
}

// WriteToRequest writes these params to a [runtime.ClientRequest].
func (o *PipelineServiceGetPipelineVersionByNameParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {
	if err := r.SetTimeout(o.inner.timeout); err != nil {
		return err
	}
	var res []error

	// path param name
	if err := r.SetPathParam("name", o.Name); err != nil {
		return err
	}

	// path param pipeline_id
	if err := r.SetPathParam("pipeline_id", o.PipelineID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
